{
  description = "silktouch: bidirectional config fragment merger";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let pkgs = import nixpkgs { inherit system; };
      in {
        devShells.default = pkgs.mkShell {
          nativeBuildInputs = with pkgs; [
            rustc cargo clippy rustfmt rust-analyzer cargo-nextest
            # Lint/hygiene tools so `just all` runs locally exactly what CI
            # runs in .github/workflows/ci.yml.
            cargo-deny cargo-machete typos
            just
          ];
          shellHook = ''export RUST_BACKTRACE=1'';
        };

        packages.default = pkgs.rustPlatform.buildRustPackage {
          pname = "silktouch";
          version = "0.1.0";
          src = ./.;
          cargoLock.lockFile = ./Cargo.lock;

          nativeBuildInputs = [ pkgs.installShellFiles ];

          # Generated by running the binary this very derivation just
          # built, so completions and the man page can never drift from
          # the CLI they describe. Only valid because host == target here:
          # under cross compilation the binary could not be run to
          # generate them.
          # Install the COMPLETE= registration shim, NOT the ahead of time
          # scripts from `silktouch completions <shell>`. In clap_complete
          # these are two separate mechanisms: the AOT scripts know the flags
          # but nothing about values, while the shim calls back into the
          # binary on each TAB, which is what completes real --set names from
          # the registry and the --merge strategy names. `silktouch
          # completions` stays for anyone who wants the static script.
          postInstall = ''
            installShellCompletion --cmd silktouch \
              --bash <(COMPLETE=bash $out/bin/silktouch) \
              --zsh  <(COMPLETE=zsh  $out/bin/silktouch) \
              --fish <(COMPLETE=fish $out/bin/silktouch)

            $out/bin/silktouch man > "$TMPDIR/silktouch.1"
            installManPage "$TMPDIR/silktouch.1"
          '';
        };
      });
}
